### PR TITLE
Pivot to internal types

### PR DESCRIPTION
**Pull request by jyaworski**
Solves #70. Work in progress.

### CODE REVIEW

**Comment by jyaworski** [comment]
Adding to this, I'd like guidance on how to handle selmodule. It looks like it takes the .pp file and installs it. Does that just replace the exec, or do we refactor this?

**Comment by jyaworski** [comment]
Hmm. This is also failing on Ruby 1.8.7. Ideas?

**Comment by jyaworski** [comment]
Added some initial module work and did some refactoring in the process.

Note: isn't make installed with selinux? If it isn't, I can put back use_makefile.

**Comment by jyaworski** [comment]
Tag @jfryman (if you didn't get the notification)

**Comment by jfryman** [comment]
It looks like this is failing on more than Ruby 1.8.7. If that's all that is failing, I think it's acceptable to deprecate as Puppet doesn't support that version of ruby anymore either.

The rest though, should pass. :)

What it looks like is that the negative lookahead in your regex is causing a problem. This wasn't able to be done until 1.9.3. Can you do https://github.com/jfryman/puppet-selinux/pull/73/files#diff-5db2390a154a0e185d52ce1303d25943R46 without the lookahead?

**Comment by jyaworski** [comment]
OK, this is in a reasonable state, but don't merge yet. I'm going to do more internal testing to make sure it makes sense and it flows well. Feel free to look over it in the meantime.

**Comment by jyaworski** [comment]
Just as an FYI: this likely deserves whatever you consider a major version bump. I ended up dropping Ruby 1.8.7 support, as you stated it's no longer supported by upstream puppet.

**Comment by jfryman** [comment]
> Just as an FYI: this likely deserves whatever you consider a major version bump. I ended up dropping Ruby 1.8.7 support, as you stated it's no longer supported by upstream puppet.

:+1:

**Comment by jyaworski** [comment]
@jfryman we're good to go.

**Comment by jfryman** [comment]
@jyaworski will you rebase, I'll merge this in as well.

**Comment by jyaworski** [comment]
OK, rebased.

**Pull request merged**
