### PR TITLE
fedora support

### PR DESCRIPTION
**Pull request by jhoblitt**
Based on #42

### CODE REVIEW

**Comment by jhoblitt** [comment]
Rebased on current master as #42 has been merged.

**Comment by jhoblitt** [comment]
:clap:

**Comment by mgoodness** [comment]
This has broken CentOS support.

**Comment by jhoblitt** [comment]
@mgoodness What version of centos? What version of puppet? What version of facter? What is the error message?

**Comment by jhoblitt** [comment]
I think I see the problem, the case statement on $::operatingsystem needs to default to everything but fedora.

**Comment by mgoodness** [comment]
Apologies for the lack of detail.

CentOS 6.6, Puppet 3.8.1, Facter 2.4.4
Error is "CentOS is not supported". I believe the $::operatingsystem case statement is the cause, yes.

**Comment by jhoblitt** [comment]
@mgoodness Could you give #44 a try?

**Comment by mgoodness** [comment]
LGTM. Thank you, sir!

**Pull request merged**
