### PR TITLE
Feature: add support for templating .te files

### PR DESCRIPTION
**Pull request by gavinrogers**
Hi,

I needed to be able to support this, and I think it might be useful for others. Basically, source doesn't support templates, meaning .te files can only be static. Using content, we can still use the file() function, but also use template(). I've changed the README to reflect the change. Please ping me if there's any additional garnishes that you'd like.

### CODE REVIEW

**Comment by jfryman** [comment]
Nice. Thanks.

I like the change, but I think this should be an AND, not an OR. It will break existing users with this change.

**Comment by gavinrogers** [comment]
Ok, done. I've left the documentation as showing the content option (in the interest of simplicity), but now source will work equally well, for backwards compatibility reasons and also edge cases (which I can't really imagine at this stage).

**Comment by jyaworski** [comment]
Hello:

Is this still needed? If so, can you rebase?

**Comment by jfryman** [comment]
Going to close this. If you'd still like to give it a go, please reopen. Thanks for your contribution!

**Pull request closed without merging**
