### PR TITLE
Added Support for defining file types in fcontext defined type

### PR DESCRIPTION
**Pull request by exodusftw**

### CODE REVIEW

**Comment by jfryman** [comment]
Right on! Thanks for the code.

**Comment by exodusftw** [comment]
Awesome! I'll have to work with the fork jgazeley has up on puppet forge to get it included there (https://forge.puppetlabs.com/jgazeley/selinux )

--- Original Message ---

**Comment by jfryman** [comment]
Let me just push this up to the forge.

**Comment by jfryman** [comment]
https://forge.puppetlabs.com/jfryman/selinux

**Pull request merged**
