### PR TITLE
added hiera support

### PR DESCRIPTION
**Pull request by dacron**
Added hiera support for fcontext, boolean, module, and port.

### CODE REVIEW

**Comment by jyaworski** [comment]
Hello:

Is this still needed? If so, can you rebase?

**Comment by dacron** [comment]
It would be pretty handy to have these lookups. Rebase done.

**Comment by jyaworski** [comment]
Thanks. Some tests fail, but it looks like some are for older versions of ruby/puppet. We may deprecate those as part of #73. @jfryman?

**Comment by jfryman** [comment]
@jyaworski if it makes sense to remove older tests, go for it. :dancer:

**Comment by jfryman** [comment]
@jyaworski I also added a note to the README. 1.9.3+ only going forward.

**Comment by jyaworski** [comment]
@dacron can you rebase?

**Comment by dacron** [comment]
Done!

**Comment by jyaworski** [comment]
@dacron could you squash your two commits into one?

**Comment by jfryman** [comment]
Thanks for the contribution! :bow:

**Pull request merged**
